### ISSUE TITLE
Add a "monthly" option for frequency?

### ISSUE THREAD

**Issue by ravi** [rogerc/file-stream-rotator#11]
Most logs do not grow fast enough, by my estimate (wrong?), to be rotated "daily". A "monthly" option would be nice to have. I could try to use "Xm" and calculate (X as 30_24_60) but that assumes all months have 30 days.

I can submit a PR if there is interest.

**Comment by hxroger** [comment]
Ravi thanks for the feedback. We are looking at refactoring the module. We will include the monthly option for the defined rotation.

**Comment by rogerc** [comment]
Hi Ravi,

You can use monthly by using a date format that will only change once a month (at the start of each month).

// Rotate when the date format as calculated by momentjs is different (e.g monthly)
    var rotatingLogStream = require('file-stream-rotator').getStream({filename:"/tmp/test-%DATE%.log", frequency:"custom", verbose: false, date_format: "YYYY-MM"});
