### ISSUE TITLE
Rotation breaks if %DATE% is a directory

### ISSUE THREAD

**Issue by joewalker** [rogerc/file-stream-rotator#13]
fs.createWriteStream will create a new file, but if it's in a directory that doesn't exist, you're going to have a bad day.

**Comment by hx-markterry** [comment]
looks good to me

**Comment by rogerc** [comment]
Fixed in latest commit 74f2709d545135354ae6a6c797813355bbf9d106.

@joewalker Thanks for creating pull request. I preferred not to include another dependency. Used split/reduce to cycle through the path.
