### ISSUE TITLE
file-stream-rotator can't work with PM2

### ISSUE THREAD

**Issue by MallowEra** [rogerc/file-stream-rotator#29]
My project run well when I print node app.js
But When I set 'filename'  option I can't browse my page 
then I remove this option. the page is running well,but log file not generate...

**Comment by rogerc** [comment]
Can you provide more information? Is the path accessible by the script?

**Comment by rogerc** [comment]
Closing issue as no more info provided. Reopen if issue still persists with more info. Thanks
