### ISSUE TITLE
option for UTC?

### ISSUE THREAD

**Issue by olsonpm** [rogerc/file-stream-rotator#31]
I would create a PR if you would be open to an option for writing times in UTC.  I've just had issues in the past with logs in varying timezones and it was a hassle to manage.

**Comment by rogerc** [comment]
Hi.

You can add the UTC offset to the log file using the date_format option by adding Z to the string like below.

`m().format("YYYYMMDDHHmmZ")` which outputs `'201806200848+01:00'`.

If you mean on using m().utc() instead so the date is always UTC, I can add that change. Only thing to consider is that depending on what is actually being logged, the dates in the log if not UTC won't match the dates on the file names.

Let me know your thoughts.

Roger

**Comment by olsonpm** [comment]
I didn't think about using the date format.  That works just fine, though I'm a little confused when you say

> If you mean on using m().utc() insead so the date is always UTC

Because won't the date always be UTC also with the date format?

**Comment by rogerc** [comment]
what i meant is that using date format the timezone offset is appended, e.g. as below.

> let m = require("moment");
> m().utc().format("YYYYMMDDHHmm");
'201806202142'
> m().format("YYYYMMDDHHmmZ");
'201806202242+01:00'

**Comment by olsonpm** [comment]
ok I should have assumed that's what you were saying.  I don't have a need for that - really I was only concerned with the output being machine-readable.

Thanks for your help, and the library of course.

**Comment by mscottnelson** [comment]
I would greatly appreciate a UTC option as the baseline time, ie `m().utc().format("YYYMMDDHHmm")`. We log everything in UTC so that our logs can be easily rectified across timezones. Can we reopen this issue? Let me know if you'd like a PR.

**Comment by mscottnelson** [comment]
@rogerc is this still potentially an option?

**Comment by rogerc** [comment]
@mscottnelson Do you mean the data of the filename or dates logged in the files themselves?

**Comment by mscottnelson** [comment]
I mean the date of the filename. As we format all dates, everywhere, as UTC (including log filenames from other applications on the same server), it would be usefully consistent for us to date our filename as UTC.

**Comment by IvayloB9** [comment]
The issue is that filenames are not consistent even within the same timezone.  In the very least `moment()` should be anchored to the `local()` timezone of the server.  For UTC there could be an optional flag which, if set, would anchor the timezone to UTC but there is no reason for `moment()` to jump around and pick random timezones which is what it does now.

**Comment by mscottnelson** [comment]
Unfortunately, this will help but not entirely resolve the issue, as I noticed while looking at implementing a comparable fix for handling utc. See issue https://github.com/rogerc/file-stream-rotator/issues/53

**Comment by rogerc** [comment]
@mscottnelson @olsonpm this has been resolved. I've added a new boolean option when creating the stream where you can choose to use UTC instead of local.

**Comment by mscottnelson** [comment]
Thanks @rogerc!

**Comment by IvayloB9** [comment]
Thank you, much appreciated! 👍 😄
