### ISSUE TITLE
rotator attempts to delete the file that does not exist.

### ISSUE THREAD

**Issue by nazuna1** [rogerc/file-stream-rotator#33]
rotator attempts to delete the file that does not exist.

Below my log.
2018-05-10T11:46:16.430Z '[FileStreamRotator] Could not remove old log file: ' 'log/exception_2018-04-07.log'

Yes, today is May 10.
The file has already been deleted.
The Message show start node.js and midnight and raises an UnException Socket Error.
Always First Rotator's Error and Next Socket Error.
There was no problem before adding Rotator.

How do I resolve this issue?

**Comment by rogerc** [comment]
Hi.

the remove file option is used only when max number of files or days option is enabled.  If something else is removing the files before the module does the clean-up it would cause that output.

The output above should not have any relation to the socket error. Is something clearing the log folder white the process is running?

If the issue still exists, please provide sample code and sample log.

Thanks

Roger

**Comment by rogerc** [comment]
I've found a scenario where this could happen which is when the service restarts and creates another entry in the audit for the same log file. This will be fixed in 0.3.0 that will be deployed this week.

Thanks for raising the issue.
