### ISSUE TITLE
Support compression (automatically zip log files)

### ISSUE THREAD

**Issue by Simran-B** [rogerc/file-stream-rotator#38]
It would be really handy if logs could be compressed on the fly or zipped automatically on rotation.

[winston-daily-rotate-file](https://github.com/winstonjs/winston-daily-rotate-file) calls such an option **zippedArchive**: A boolean to define whether or not to gzip archived log files. (default 'false')

They seem to compress the logfile in one piece on rotation:

```js
        if (options.zippedArchive) {
            this.logStream.on('rotate', function (oldFile) {
                var gzip = zlib.createGzip();
                var inp = fs.createReadStream(oldFile);
                var out = fs.createWriteStream(oldFile + '.gz');
                inp.pipe(gzip).pipe(out).on('finish', function () {
                    fs.unlinkSync(oldFile);
                });
            });
        }
```

I guess it would be too risky to use on-the-fly compression because in case of an abrupt process termination the file could be rendered invalid...

**Comment by mattberther** [comment]
As the maintainer of https://github.com/winstonjs/winston-daily-rotate-file, I've thought through submitting a PR for this, but need to consider how to modify the audit file to remove the original log and add the gzip file. Perhaps @rogerc has some ideas on that.

**Comment by amrendra007** [comment]
with compression, will be really great if it deletes old compressed files also based on maxfile to keep.

**Comment by rogerc** [comment]
@mattberther as your module provides compression, I'd recommend (if you haven't done so already) that you track the zipped files in the same way that I do here and when the event for a new log file is fired, after you have zipped the relevant file, you delete the oldest. I feel this separation provides the best flexibility for your needs and anyone else using the package.

**Comment by gurupras** [comment]
This is difficult to make a PR for because the `auditManager` member is private. We don't have a clean way to manipulate the audit file on the `rotate` event.
