### ISSUE TITLE
Support creating new file if the file was removed

### ISSUE THREAD

**Issue by phakinch** [rogerc/file-stream-rotator#40]
There are some circumstances that log file may be removed while the stream is writing to it.  It would be great if the logic to check if file no longer exists added, and create (rotate) a new file (of the same name) should the file was removed.

`414    if (newDate != curDate || (fileSize && curSize > fileSize) `**`|| !fs.existsSync( logfile )`** `)`

**Comment by rogerc** [comment]
Hi @phakinch ,

I've looked into the scenario to find possible fixes. Unfortunately using fs.existsSync slows down my tests by 25% which this is not good. I've looked at using fs.watch but it doesn't seem to raise any event on deletion. I'll see if I can find a solution for this that doesn't impact performance over the next month. If I can't I'll close the issue then.

Thanks

Roger

**Comment by phakinch** [comment]
Hi @rogerc,

Thank you for looking into this.  Another option, if possible, is to have a function to manually rotate file, so it can be invoked by the main program to open a new file to stream to.   The main program may be triggered by signal or http request without the need to restart in order to inject data into file stream.

Thanks,

Phakin Ch.

**Comment by rogerc** [comment]
Hi @phakinch 

I'll look into creating a function to trigger the manual rotation which in the event of the original file  missing, it would create it again. 

Roger

**Comment by rogerc** [comment]
Hi @phakinch 

I'm preparing an update and revisited this issue. I've tested several ways of using fs.watcher but it seems that it only recreates the file once. If it gets deleted a second time except for a couple of times, watcher doesn't seem to pick it up. For now it will pick up at least one deletion within the current time period the log file is recording. This could be how MacOS behaves and might be OK under Linux.

Roger

**Comment by rogerc** [comment]
Hi @phakinch 

I've moved the log watcher behind the option flag 'watch_log' available when creating the stream. Please have a look at the README for more information.

Roger

**Comment by phakinch** [comment]
Hi @rogerc 

Thank you for the update.  Love it.

Cheers,
Phakin Ch.
