### ISSUE TITLE
Maybe a bug. TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by ladjzero** [rogerc/file-stream-rotator#43]
Hello, file-stream-rotator team. It seems that there are some breaking changes in this module. My package.json includes

```
"winston": "^3.0.0-rc2",
"winston-daily-rotate-file": "^3.1.4"
```

My app fails to run in recent builds due to `TypeError: Cannot read property '1' of null`. How does this come out? Should I remove all the old logs before?

```
TypeError: Cannot read property '1' of null
    at Object.FileStreamRotator.getStream (/opt/nodeapp/node_modules/file-stream-rotator/FileStreamRotator.js:396:38)
    at new DailyRotateFile (/opt/nodeapp/node_modules/winston-daily-rotate-file/daily-rotate-file.js:81:57)
```

relates to https://github.com/rogerc/file-stream-rotator/blob/master/FileStreamRotator.js#L396

**Comment by rogerc** [comment]
Hi @ladjzero 

issue has been fixed. I've pushed v0.3.1 to NPM so you can download the latest. @andrefarzat had raised a PR for this (thanks for raising it) but hadn't had a chance to review and approve it as there were quite a few changes to the files.

Thanks for raising the issue.

Roger
