### ISSUE TITLE
Keep same file name and archive files with timeStamp

### ISSUE THREAD

**Issue by rotosonic** [rogerc/file-stream-rotator#44]
Is it possible to keep logging to a file with the same name and add a timeformat to archive files

**Comment by rogerc** [comment]
Hi @rotosonic,

The reason I didn't go down that route was to reduce the amount of work required when doing rotation and avoid issues moving/renaming files when doing the rotation.

An alternative to this would be creating a symbolic link to the current file being written to with the option to specify what that name should be so if you wanted to see what the current file being written was you would just go to the filename specified when initialising the stream. Would that work?

Roger

**Comment by rogerc** [comment]
After some testing, if a link already exists it won't overwrite it so I'd need to unlink the 'file' if it cannot complete the symbolic link creation. I'll run some benchmarks to see how much of an issue that is.

**Comment by LiangNex** [comment]
Hi @rogerc ,

Do we have any update on this issue? 

What do you think of adding a new option like ```date_format_archive_only``` as conditions [here](https://github.com/rogerc/file-stream-rotator/blob/822b8a5241335ddc01208df2d1c6f54250cc0491/FileStreamRotator.js#L383) to implement this feature?

Thanks 
Liang

**Comment by bellostom** [comment]
Any news on this one?
I ended up here from
https://github.com/winstonjs/winston-daily-rotate-file/issues/23
which is already mentioned above, as currently frequent log rotations, makes tracking the latest log file difficult

**Comment by rogerc** [comment]
v0.5.0 will add a symbolic link to the current log file which you can access via current.log
