### ISSUE TITLE
File extension support for rotational files

### ISSUE THREAD

**Issue by johnson-tito** [rogerc/file-stream-rotator#48]
Hi,

I have a situation where I need my files to have an extension(filename.ext). When I configure the file name as follow,

`fileStreamRotator.getStream({
    frequency: "daily",
    filename:"filename-%DATE%.ext"
  });`

on file rotation the file name is suffixed with a counter as follow _filename-DATE.ext.1_ , _filename-DATE.ext.2_ and so on, but actually my requirement is _filename-DATE-1.ext_, filename-DATE-2.ext. I need the extension to be suffixed at last, instead of the counter.

Something like this will do great.

`fileStreamRotator.getStream({
    frequency: "daily",
    filename:"filename-%DATE%",
    extension: "ext"
  });`

**Comment by rogerc** [comment]
@johnson-tito @mattberther last commit has support for extension. I'd appreciate if you could test it in your environment before I release v0.5.1. The readme shows the new option for the extension. Thanks

**Comment by rogerc** [comment]
v0.5.3 has been published that includes this change

**Comment by mattberther** [comment]
@rogerc I just noticed that the extension only happens with a rotation event. The following script:

```
var os = require('os');

var logStream = require('file-stream-rotator').getStream({
    filename: './logs/application-%DATE%',
    frequency: 'custom',
    extension: '.testlog',
    end_stream: true
});

for (var i = 0; i < 10; i++) {
    logStream.write(randomString(1056) + os.eol);
}
```

results in a single file without the .testlog extension. However, once rotation is added using the `size` option, things work fine. Any chance we can have the extension applied in all cases?

**Comment by rogerc** [comment]
@mattberther I've fixed the issue and also fixed another issue that wasn't rotating when just using file size as the condition. I've pushed v 0.5.4 to npm.
