### ISSUE TITLE
Format of date varies depending on what time of day the getStream function was run

### ISSUE THREAD

**Issue by mscottnelson** [rogerc/file-stream-rotator#53]
The behavior of file-stream-rotator varies depending on when it starts up. Note the following code snippet from FileStreamRotator.getStream
```
var dateFormat = (options.date_format || DATE_FORMAT);
    if(frequencyMetaData && frequencyMetaData.type == "daily"){
        if(!options.date_format){
            dateFormat = "YYYY-MM-DD";
        }
        if(moment().format(dateFormat) != moment().add(2,"hours").format(dateFormat) || moment().format(dateFormat) == moment().add(1,"day").format(dateFormat)){
            if(options.verbose){
                console.log(new Date(),"[FileStreamRotator] Changing type to custom as date format changes more often than once a day or not every day");
            }
            frequencyMetaData.type = "custom";
        }
    }
```
The value of moment() is dependent on the time of day getStream is run. Therefore, comparing moment() with moment().add(2,"hours") to discover if you are on the same day or not will result in different behavior depending on whether moment() is evaluated at eg 11:30pm or 11:30am.

Please let me know if you would accept an MR to fix this issue.

**Comment by rogerc** [comment]
Hi @mscottnelson,

Thanks for raising this. I've fixed this using moment().endof("day") to compare same day DATE_FORMAT.

I will be releasing the fix with v0.5.0 later today.
