### ISSUE TITLE
Is it possible make creating symbolic link "current.log" configurable?

### ISSUE THREAD

**Issue by ifree92** [rogerc/file-stream-rotator#57]
https://github.com/rogerc/file-stream-rotator/blob/77e8ba9d4bbdc09b0046c4cd984376875a791f64/FileStreamRotator.js#L520

I would like to have an option to disable a creating symbolic link on a "current.log" file.
Why this is forced?

Thank you!

**Comment by mattberther** [comment]
A PR is available at https://github.com/rogerc/file-stream-rotator/pull/58.

**Comment by rogerc** [comment]
Accepted PR. I've made a further change to allow to change the name of the symbolic link. I've published v0.5.5

**Comment by YouDevByRahulAkhouri** [comment]
Hi @mattberther 

**symlink not getting created in winston-daily-rotate:**
 i wanted current file to always be app.log without the date extention. seems like winston will append date to current file also. So added symlink of name app.log which would be pointing to currentFile i.e app.log-2021-12-22-05-48(say)
note: trying every min rotation for dev testing.


 my code:

const logFile = /opt/ssbt-gui-workspace/log/app.log
const logger = createLogger({
    level: "debug",
    format: combine(timestamp(), json()),
    transports: [
        new DailyRotateFile({filename:`${logFile}`,datePattern:"YYYY-MM-DD-HH-mm", zippedArchive: true,maxSize:"10m",maxFiles:"7d", utc:true,auditFile:"Audit-app.log",createSymlink:true,symlinkName:`${logFile}`})
        .on("new", (newFilename) => {
          logger.info(`New log fileName: ${newFilename}`);
          }).on("rotate", (oldFilename, newFilename) => {
            logger.info(`Rotated log files. Old_File_Name: ${oldFilename} New_File_Name: ${newFilename}`);
          }).on("archive", (zipFilename) => {
            logger.info(`Archived Log file. zipFilename: ${zipFilename}`);
          }).on("logRemoved", (removedFilename) => {
            logger.info(`Deleted the old log file. Deleted_File_Name ${removedFilename}`);
          }),
    ]
});

could you(or anyone on behalf of Matt) please help in resolving the issue?

## package version:
"winston": "^3.3.3",
   "winston-daily-rotate-file": "^4.5.5"
