### ISSUE TITLE
series number foramt like .log_001

### ISSUE THREAD

**Issue by xunzhaoderen** [rogerc/file-stream-rotator#61]
whether it supports user-defined series number filename format like applicaiton_001.log,  not application.log.1

**Comment by rogerc** [comment]
release 0.6.0 will allow for application.1.log rather than application.log.1.  This could be achieve in previous version with the config below. No padded numbers unfortunately.
```js
var rotatingLogStream = require('../FileStreamRotator').getStream({
    filename:"logs/nodate/%DATE%", 
    frequency:"custom", 
    verbose: true, 
    date_format: "[LOGFILENAME]", 
    size:"50k",
    max_logs: "5", 
    audit_file:"audit-nodate.json",
    end_stream: false,
    extension: ".log"
});
```
