### ISSUE TITLE
newLogFileName is wrong in line588

### ISSUE THREAD

**Issue by dsachwani** [rogerc/file-stream-rotator#68]
Hello Roger,
I am trying to have no date appended in current/active log, for that options I gave are:
 {   level: process.env.LOG_LEVEL,
        filename: `${appRoot}/logs/mylog`,
        handleExceptions: true,
        json: true,
        maxSize: '100m', // ~100MB
        maxFiles: 15,
        colorize: false, 
        tailable: false,
        frequency: 'd',
        extension: '.log',
}

but after size exceeds the new file created is mylog.log.1 but still logging continues in mylog.log,
I guess on line 581 var newLogfile = logfileName; can be given , not sure though :) 

Please let me know if I am selecting correct options

**Comment by panbhatt** [comment]
u need to change tailable:true

**Comment by rogerc** [comment]
tailable: false, is not an option in this module so not sure if you are using a wrapper to this module or using something else completely. Closing issue.
