### ISSUE TITLE
rotator checks the size of the log before writing

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [rogerc/file-stream-rotator#74]
If the file-stream-rotator writes a record to the log and exceeds the `maxSize` size requirements informed in the transport for Winston, it will not call the rotator event and on the next run it will just create a new log

[issue for winston-daily-rotate-file](https://github.com/winstonjs/winston-daily-rotate-file/issues/288)

Here is the verification for size file, if the size exceeds, than it will create the next log, but wont zip the old one.
```javascript
        if(lastLogFile){
            var lastLogFileStats = fs.statSync(lastLogFile);
            if(lastLogFileStats.size < fileSize){
                t_log = lastLogFile;
                fileCount--;
                curSize = lastLogFileStats.size;
            } 
        }
```

Here is the verification for size file when is writing, it is necessary a check after writing to the file.
```javascript
        stream.write = (function (str, encoding) {
            var newDate = this.getDate(frequencyMetaData, dateFormat, options.utc);
            if (newDate != curDate || (fileSize && curSize > fileSize)) {
....
                stream.emit('rotate',oldFile, newLogfile);
                BubbleEvents(rotateStream,stream);
            }
            rotateStream.write(str, encoding);
            // Handle length of double-byte characters
            curSize += Buffer.byteLength(str, encoding);
```

if the last written register (before the application closes) exceeds the file size to rotate, then the next time the application is run, the first block of code above will be executed and will create a new log sequence, and the old one will be left unzipped

I openned a issue for winston-daily-rotate-file about this problem: [issue for winston-daily-rotate-file](https://github.com/winstonjs/winston-daily-rotate-file/issues/288)

**Comment by rogerc** [comment]
issue closed upstream.
