### ISSUE TITLE
Enable file-stream-rotator to become FIPS compliant

### ISSUE THREAD

**Issue by ZarifS** [rogerc/file-stream-rotator#82]
- It seems at the moment the rotator file is using the MD5 hash option for the crypto function but to turn this FIPS compliant it would be a simple change to turn the crypto function to use the new FIPS complaint hash of SHA256
- If you look here https://github.com/rogerc/file-stream-rotator/blob/master/FileStreamRotator.js#L278 the change would be to change to SHA256 
- This would make other applications which use file-stream-rotator to allow be FIPS validated, increasing the security and popularity of this package and any package which utilizes this such as https://github.com/winstonjs/winston-daily-rotate-file for example.

If this makes sense a PR for this should not be too difficult. You can even parametrize the function to allow for FIPS enablement or not for those packages that don't want a SHA256 encryption.

**Comment by shubhammane77** [comment]
Any update here? We are still facing this issue while upgrading node 8 to node 14.

**Comment by ZarifS** [comment]
I have not heard back from the devs if a PR for this is welcome or not, you can make a PR for it and see if they will accept it. We have since switched to not use this package due to the FIPS issue.

**Comment by rogerc** [comment]
@ZarifS, @shubhammane77 I've pushed 0.6.0 to GitHub. I'd appreciate if you looked at the changes I made to support different hashing algorithms in the audit log. I've also updated moments to 2.29.1. When I deploy it NPM, I'll update the minimum node version to 12.22.9.

**Comment by shubhammane77** [comment]
@rogerc  Thanks for the PR. Looks good to go.

**Comment by rogerc** [comment]
version 0.6.0 has been published
