### ISSUE TITLE
Daily rotation is completely broken

### ISSUE THREAD

**Issue by joepie91** [rogerc/file-stream-rotator#9]
Specifying `daily` as the `frequency` is completely broken. It will create a new logfile every minute.

The culprit is [here](https://github.com/holidayextras/file-stream-rotator/blob/b661b1c5061ca812445443628ef2e55670cfabe3/FileStreamRotator.js#L156), which triggers every minute because [`getDate` always returns the current minute for `daily` rotation](https://github.com/holidayextras/file-stream-rotator/blob/b661b1c5061ca812445443628ef2e55670cfabe3/FileStreamRotator.js#L116).

As I find the code very hard to read and understand and the test coverage evidently isn't sufficient, I've decided not to make a pull request - this would be likely to break some other piece of functionality.

**Comment by mrphelz** [comment]
it's not clearly documented, but if you set a date_format in options you can have a log file for each day

example:
```javascript
var accessLogStream = require('file-stream-rotator').getStream({
  filename   : logDirectory + '/access-%DATE%.log',
  frequency  : 'daily',
  verbose    : false,
  date_format: 'YYYYMMDD'
});
```

**Comment by hxroger** [comment]
Will fix this. Thanks for raising it.

Issue is that since introducing date format in file, it defaults to rotation every minute.

**Comment by exterry** [comment]
I get something similar:

    /Users/exterry/Desktop/shuren_app/node_modules/file-stream-rotator/FileStreamRotator.js:132
        frequencyMetaData = self.getFrequency(options.frequency);
                                ^
TypeError: Cannot read property 'getFrequency' of undefined
    at FileStreamRotator.getStream (/Users/exterry/Desktop/shuren_app/node_modules/file-stream-rotator/FileStreamRotator.js:132:33)
    at Object.<anonymous> (/Users/exterry/Desktop/shuren_app/app.js:64:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/exterry/Desktop/shuren_app/bin/www:7:11)
    at Module._compile (module.js:460:26)

**Comment by MForever78** [comment]
Same as @exterry 

Can this be fixed soon? I have to remove this module to get my app running.

**Comment by julestruong** [comment]
@pdesterlich i'm sorry this solution doesn't work.

**Comment by rogerc** [comment]
not seeing any errors in latest release planned this week so closing this issue
